/* ============================================================
   PROLAUNCH / GLAMLAUNCH — Brand Content Config
   ============================================================ */

const BRAND_CONTENT = {
  prolaunch: {
    'hero-eyebrow': 'Creative Agency',
    'hero-headline-1': 'Get Your Business',
    'hero-headline-2': '',
    'hero-headline-mid': 'Online \u2014',
    'hero-headline-fast': 'Fast.',
    'hero-headline-suffix': '',
    'hero-sub': 'Custom websites, and marketing to get your brand live and thriving.',
    'svc-heading-1': 'Everything You Need to',
    'svc-heading-em': 'Thrive',
    'svc-websites-title': 'Websites',
    'svc-websites-desc': 'Custom-built sites that look premium and convert visitors into clients.',
    'svc-landing-title': 'Landing Pages',
    'svc-landing-desc': 'High-converting single pages designed to capture leads and drive action.',
    'svc-social-content-title': 'Social Media Content',
    'svc-social-content-desc': 'Scroll-stopping graphics, reels, and captions that grow your audience.',
    'svc-social-mgmt-title': 'Social Media Management',
    'svc-social-mgmt-desc': 'We handle your posting, scheduling, and engagement so you can focus on your business.',
    'svc-avatars-title': 'Marketing Campaigns',
    'svc-avatars-desc': 'Launch campaigns, funnels, and nurture sequences that turn one-time visitors into loyal customers.',
    'svc-appdev-title': 'App Development',
    'svc-appdev-desc': 'Custom mobile and web apps built to scale your business and engage your customers.',
    'svc-templates-title': 'Squarespace Templates',
    'svc-templates-desc': 'Premium, ready-to-use templates so you can launch your site today.',
    'why-heading-1': 'Built for Speed.',
    'why-heading-em': 'Growth.',
    'cta-heading-em': 'Begin?',
    'cta-sub': 'Book a free consultation and let\'s get your business online.',
    'services-hero-heading-em': 'Grow',
    'services-hero-sub': 'From custom websites to AI-powered avatars, we build the digital foundation your business needs to thrive.',
    'svc-websites-h2-em': 'Custom',
    'svc-websites-h2-rest': 'Websites',
    'svc-websites-p': 'We design and build fully custom websites tailored to your brand. No templates, no cookie-cutter designs \u2014 every site is built from scratch to represent your unique business and convert visitors into customers.',
    'svc-landing-h2-em': 'Landing',
    'svc-landing-h2-rest': 'Pages',
    'svc-social-content-h2-pre': 'Social Media',
    'svc-social-content-h2-em': 'Content',
    'svc-social-mgmt-h2-pre': 'Social Media',
    'svc-social-mgmt-h2-em': 'Management',
    'svc-avatars-h2-pre': 'Marketing',
    'svc-avatars-h2-em': 'Campaigns',
    'svc-appdev-h2-em': 'App',
    'svc-appdev-h2-rest': 'Development',
    'svc-appdev-p': 'From concept to launch, we build custom mobile and web applications that solve real problems for your business. Whether it\'s a customer-facing app, an internal tool, or a full SaaS product \u2014 we bring your idea to life.',
    'svc-cta-heading': 'Not Sure What You Need?',
    'svc-cta-sub': 'Book a free consultation. We\'ll figure out the best package for your business together.',
    'shop-hero-heading-em': 'Website',
    'shop-hero-sub': 'Professionally designed, ready to go. Pick a template, customize it, and start selling today.',
    'shop-cta-sub': 'Our templates are great for getting started. When you\'re ready for a fully custom site, we\'re here.',
    'portfolio-hero-heading-1': 'Projects That',
    'portfolio-hero-heading-em': 'Perform',
    'portfolio-hero-sub': 'Real results for real businesses. Here\'s what we\'ve built.',
    'about-hero-heading-1': 'The Agency Behind',
    'about-hero-heading-em': 'Growth',
    'about-hero-sub': 'We exist to make getting online simple, fast, and beautiful.',
    'about-story-h2-1': 'We\'ve Been Where',
    'about-story-h2-em': 'You Are',
    'about-story-p1': 'ProLaunch was born from a simple frustration: getting a business online shouldn\'t be this hard. Too many entrepreneurs spend months trying to figure out websites, social media, and marketing \u2014 time they should be spending on their business.',
    'about-story-p2': 'We built ProLaunch to change that. We combine premium design, strategic marketing, and AI-powered tools to get businesses launched and growing \u2014 fast. No jargon, no delays, no cookie-cutter solutions.',
    'about-cta-heading-em': 'Together?',
    'about-cta-sub': 'Let\'s build something great for your business.',
    'contact-hero-heading-1': 'Let\'s',
    'contact-hero-heading-em': 'Build',
    'contact-hero-heading-2': 'Your Business',
    'contact-hero-sub': 'Book a free consultation or send us a message. We\'ll get back to you within 24 hours.',
    'blog-hero-sub': 'We\'re working on something good. In the meantime, follow us on social for tips and updates.',
  },
  glamlaunch: {
    'hero-eyebrow': 'Creative Agency',
    'hero-headline-1': 'Elevate Your',
    'hero-headline-2': 'Beauty',
    'hero-headline-mid': 'Brand Online \u2014',
    'hero-headline-fast': '',
    'hero-headline-suffix': 'Effortlessly.',
    'hero-sub': 'Stunning websites, social media, and AI-powered avatars for glam brands, salons, medspas, and lifestyle businesses.',
    'svc-heading-1': 'Everything You Need to',
    'svc-heading-em': 'Glow',
    'svc-websites-title': 'Glam Brand Websites',
    'svc-websites-desc': 'Custom-built sites that showcase your brand and book more appointments.',
    'svc-landing-title': 'Promo & Launch Pages',
    'svc-landing-desc': 'High-converting pages for new launches, seasonal promos, and events.',
    'svc-social-content-title': 'Glam Content Creation',
    'svc-social-content-desc': 'Scroll-stopping visuals, reels, and captions that attract your ideal clients.',
    'svc-social-mgmt-title': 'Social Media Management',
    'svc-social-mgmt-desc': 'We handle your posting, scheduling, and engagement so you can focus on your clients.',
    'svc-avatars-title': 'Marketing Campaigns',
    'svc-avatars-desc': 'Beauty launch campaigns, lead funnels, and client nurture sequences built for glam brands.',
    'svc-appdev-title': 'Booking & Client Apps',
    'svc-appdev-desc': 'Custom booking apps and client portals built to streamline your business.',
    'svc-templates-title': 'Glam Squarespace Templates',
    'svc-templates-desc': 'Premium templates designed for glam brands so you can get online today.',
    'why-heading-1': 'Built for Glam.',
    'why-heading-em': 'Growth.',
    'cta-heading-em': 'Glow?',
    'cta-sub': 'Book a free consultation and let\'s elevate your glam brand.',
    'services-hero-heading-em': 'Glow',
    'services-hero-sub': 'From glam brand websites to AI ambassadors, we build the digital foundation your brand needs to thrive.',
    'svc-websites-h2-em': 'Glam Brand',
    'svc-websites-h2-rest': 'Websites',
    'svc-websites-p': 'We design and build fully custom websites tailored to your brand. No generic templates \u2014 every site is crafted to showcase your services, your story, and book more clients.',
    'svc-landing-h2-em': 'Promo & Launch',
    'svc-landing-h2-rest': 'Pages',
    'svc-social-content-h2-pre': 'Glam',
    'svc-social-content-h2-em': 'Content',
    'svc-social-mgmt-h2-pre': 'Social Media',
    'svc-social-mgmt-h2-em': 'Management',
    'svc-avatars-h2-pre': 'Marketing',
    'svc-avatars-h2-em': 'Campaigns',
    'svc-appdev-h2-em': 'Booking & Client',
    'svc-appdev-h2-rest': 'Apps',
    'svc-appdev-p': 'From concept to completion, we build custom booking apps and client portals that solve real problems for your business. Whether it\'s online scheduling, client galleries, or a loyalty program \u2014 we bring your idea to life.',
    'svc-cta-heading': 'Not Sure Where to Start?',
    'svc-cta-sub': 'Book a free consultation. We\'ll figure out the perfect package for your brand together.',
    'shop-hero-heading-em': 'Website',
    'shop-hero-sub': 'Professionally designed for glam brands. Pick a template, customize it, and start booking today.',
    'shop-cta-sub': 'Our glam templates are great for getting started. When you\'re ready for a fully custom site, we\'re here.',
    'portfolio-hero-heading-1': 'Glam Brands That',
    'portfolio-hero-heading-em': 'Shine',
    'portfolio-hero-sub': 'Real results for real brands. Here\'s what we\'ve built.',
    'about-hero-heading-1': 'The Agency Behind',
    'about-hero-heading-em': 'Glow',
    'about-hero-sub': 'We exist to make glam brands look stunning online.',
    'about-story-h2-1': 'We Know',
    'about-story-h2-em': 'Glam',
    'about-story-p1': 'GlamLaunch was born from a passion for glam brands \u2014 beauty, fashion, lifestyle, and wellness. Too many talented entrepreneurs are held back by a weak online presence.',
    'about-story-p2': 'We built GlamLaunch to change that. We combine premium design, brand marketing expertise, and AI-powered tools to get glam brands seen, booked, and growing.',
    'about-cta-heading-em': 'Glow Up?',
    'about-cta-sub': 'Let\'s build something stunning for your brand.',
    'contact-hero-heading-1': 'Let\'s',
    'contact-hero-heading-em': 'Elevate',
    'contact-hero-heading-2': 'Your Brand',
    'contact-hero-sub': 'Book a free brand consultation. We\'ll get back to you within 24 hours.',
    'blog-hero-sub': 'We\'re working on glam brand tips and resources. Follow us for updates.',
  }
};

const BRAND_IMAGES = {
  prolaunch: {
    'hero-bg': 'images/hero-bg.jpg',
    'about-photo': 'images/about-entrepreneur.jpg',
    'svc-websites-img': 'images/workspace-1.jpg',
    'svc-landing-img': 'images/landing-pages.jpg',
    'svc-social-content-img': 'images/entrepreneur-dark.jpg',
    'svc-social-mgmt-img': 'images/about-entrepreneur.jpg',
    'svc-avatars-img': 'images/marketing-campaigns.jpg',
    'svc-appdev-img': 'images/app-development.jpg',
    'team-photo': 'images/victoria-headshot.png',
    'portfolio-1': 'images/workspace-1.jpg',
    'portfolio-2': 'images/workspace-2.jpg',
    'portfolio-3': 'images/entrepreneur-dark.jpg',
    'portfolio-4': 'images/studio-interior.jpg',
    'portfolio-5': 'images/entrepreneur-laptop.jpg',
    'portfolio-6': 'images/about-entrepreneur.jpg',
  },
  glamlaunch: {
    'hero-bg': 'images/glam-hero.jpg',
    'about-photo': 'images/glam-about.webp',
    'svc-websites-img': 'images/glam-websites.jpg',
    'svc-landing-img': 'images/landing-pages.jpg',
    'svc-social-content-img': 'images/glam-social-content.png',
    'svc-social-mgmt-img': 'images/glam-social-mgmt.jpg',
    'svc-avatars-img': 'images/marketing-campaigns.jpg',
    'svc-appdev-img': 'images/app-development.jpg',
    'team-photo': 'images/glam-team.png',
    'portfolio-1': 'images/glam-portfolio-1.jpg',
    'portfolio-2': 'images/glam-portfolio-2.png',
    'portfolio-3': 'images/glam-portfolio-3.png',
    'portfolio-4': 'images/glam-portfolio-4.jpg',
    'portfolio-5': 'images/glam-portfolio-5.jpeg',
    'portfolio-6': 'images/glam-portfolio-6.jpg',
  }
};
